name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install bats
        run: npm install -g bats
      - name: Check bats version
        run: bats --version